server:
  port: 9898
  servlet:
    context-path: "/api"
spring:
  cloud:
    nacos:
      discovery:
        server-addr: "114.55.167.88:8848"
  application:
    name: nacos-config-client

user:
  test: 123
