server:
  port: 8866
spring:
  redis:
    # 16 个数据  0-15
    database: 0
    host: 47.96.113.187
    port: 6379
    password: ""
    jedis:
      pool:
        max-active: 8
        max-idle: 6
        max-wait: -1
        min-idle: 0
