server:
  port: 9000
spring:
  application:
    name: feign-cutomer-server
  cloud:
    nacos:
      discovery:
        server-addr: 114.55.167.88:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      #        dashboard: 47.96.133.187:8858

feign:
  sentinel:
    enabled: true